# Lab | Comparing regression models

For this lab, we will be using the same dataset we used in the previous labs. We recommend using the same notebook since you will be reusing the same variables you previous created and used in labs.

# Instructions
1. In this final lab, we will model our data. Import sklearn train_test_split and separate the data.
2. Try a simple linear regression with all the data to see whether we are getting good results.
3. Great! Now define a function that takes a list of models and train (and tests) them so we can try a lot of them without repeating code.
4. Use the function to check LinearRegressor and KNeighborsRegressor.
5. You can check also the MLPRegressor for this task!
6. Check and discuss the results.

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from sklearn.preprocessing import Normalizer
import statsmodels.api as sm
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

# 1. In this final lab, we will model our data. Import sklearn train_test_split and separate the data.

In [17]:
categorical_wrg = pd.read_csv('categorcial_wrg.csv',index_col=0)
numericals = pd.read_csv('numericals.csv')
y = pd.read_csv('y.csv',index_col=0)

In [18]:
cat_encode = pd.DataFrame(OneHotEncoder().fit(pd.DataFrame(categorical_wrg)).transform(pd.DataFrame(categorical_wrg)).toarray())

In [19]:
X = pd.DataFrame(np.concatenate((numericals, cat_encode), axis=1))
X

,0,1,2,3,4,5,6,7,8,9,...,42,43,44,45,46,47,48,49,50,51
0,0.0,0.050822,0.791605,0.012882,0.601481,0.093981,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,1.0,0.047167,0.656524,0.011743,0.222572,0.719079,0.0,8.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,2.0,0.047442,0.694980,0.011704,0.307095,0.648312,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,3.0,0.035539,0.493917,0.008836,0.231848,0.837229,0.0,7.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,4.0,0.044672,0.656199,0.011320,0.198175,0.726640,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9129,9129.0,0.027681,0.440527,0.006774,0.177872,0.879480,0.0,2.0,0.0,1.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9130,9130.0,0.058899,0.730575,0.014895,0.304161,0.608322,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9131,9131.0,0.051040,0.708595,0.012671,0.166310,0.683717,3.0,2.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9132,9132.0,0.057364,0.701900,0.014264,0.707071,0.062389,0.0,3.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9133,9133.0,0.027577,0.391631,0.007002,0.030639,0.919172,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [20]:
y

      total_claim_amount
0             384.811147
1            1131.464935
2             566.472247
3             529.881344
4             138.130879
...                  ...
9129          198.234764
9130          379.200000
9131          790.784983
9132          691.200000
9133          369.600000

[9134 rows x 1 columns]

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.4, random_state=100)

# 2.Try a simple linear regression with all the data to see whether we are getting good results.

In [22]:
model = sm.OLS(y_train, X_train).fit()
predictions = model.predict(X_test)
r2_score(y_test, predictions)

0.7564944703941192

# 3. Great! Now define a function that takes a list of models and train (and tests) them so we can try a lot of them without repeating code.

4. Use the function to check LinearRegressor and KNeighborsRegressor.

5. You can check also the MLPRegressor for this task!

In [23]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor

def model_evaluation(models_list, X_train, y_train, X_test, y_test):
    
    results = []
    
    for model in models_list:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        
        mse = mean_squared_error(y_test, y_pred)
        r2 = r2_score(y_test, y_pred)
        mae = mean_absolute_error(y_test, y_pred)
        
        results.append({
            'model': type(model).__name__,
            'mse': mse,
            'r2': r2,
            'mae': mae
        })
        
    return results

In [24]:
models = [LinearRegression(), KNeighborsRegressor(), MLPRegressor()]
results = model_evaluation(models, X_train, y_train, X_test, y_test)

/Users/macbook/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:1599: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [25]:
results

[{'model': 'LinearRegression',
  'mse': 19347.221913701123,
  'r2': 0.7564944703941059,
  'mae': 98.10228264902571},
 {'model': 'KNeighborsRegressor',
  'mse': 94697.467452109,
  'r2': -0.19186915140166882,
  'mae': 228.739455872578},
 {'model': 'MLPRegressor',
  'mse': 23863.64274757089,
  'r2': 0.6996504722231991,
  'mae': 99.19776764420487}]

# 6 .Check and discuss the results.

The linear regression model is that have best accuracy .